// Strips network permissions from the RELEASE build only. Debug/dev-client builds keep INTERNET
// so they can reach Metro; the shipped APK cannot open a socket at all ("100% offline" is enforced
// by the OS, not just by convention). Remove this plugin from app.config.ts to revert.
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

const RELEASE_MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withReleaseOffline.js. Do not edit; re-run prebuild instead. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    <uses-permission android:name="android.permission.INTERNET" tools:node="remove" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" tools:node="remove" />
</manifest>
`;

module.exports = function withReleaseOffline(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'release');
      await fs.promises.mkdir(dir, { recursive: true });
      await fs.promises.writeFile(path.join(dir, 'AndroidManifest.xml'), RELEASE_MANIFEST);
      return cfg;
    },
  ]);
};
