/**
 * Regenerates ./fontData.generated.ts from the TTFs shipped in @expo-google-fonts.
 *
 *   node src/documents/html/fonts/generateFontModule.js
 *
 * PDFs are rendered offline by expo-print's WebView, so the fonts must travel inside the HTML as
 * base64 @font-face sources. Inlining them in a TS module avoids any asset resolution at runtime
 * (release Android keeps non-image assets in res/raw, unreadable from JS without expo-asset).
 * Barlow is SIL OFL 1.1, which permits embedding.
 */
/* global __dirname */
const fs = require('fs');
const path = require('path');

const FACES = [
  { name: 'BARLOW_400', pkg: '@expo-google-fonts/barlow/400Regular/Barlow_400Regular.ttf' },
  { name: 'BARLOW_600', pkg: '@expo-google-fonts/barlow/600SemiBold/Barlow_600SemiBold.ttf' },
  {
    name: 'BARLOW_SEMI_CONDENSED_500',
    pkg: '@expo-google-fonts/barlow-semi-condensed/500Medium/BarlowSemiCondensed_500Medium.ttf',
  },
];

const lines = [
  '// GENERATED by generateFontModule.js. Do not edit. Barlow: SIL Open Font License 1.1.',
  '',
];
for (const face of FACES) {
  const base64 = fs.readFileSync(require.resolve(face.pkg)).toString('base64');
  lines.push(`export const ${face.name} = '${base64}';`, '');
}
fs.writeFileSync(path.join(__dirname, 'fontData.generated.ts'), lines.join('\n'));
